# Generated by Django 3.1.6 on 2021-02-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('con_name', models.CharField(max_length=70)),
                ('con_email', models.CharField(max_length=100)),
                ('con_phone', models.IntegerField()),
                ('con_desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
