# Generated by Django 3.1.6 on 2021-02-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_sno', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=200)),
                ('post_desc', models.CharField(max_length=10000)),
                ('post_author', models.CharField(max_length=40)),
                ('post_ts', models.DateTimeField(blank=True)),
            ],
        ),
    ]
