# Generated by Django 3.1.6 on 2021-02-06 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='comm_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
